version: '3.8'
services:
  dev-db:
    image: postgres:13.6
    environment:
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    ports:
      - "5486:5486"
    volumes:
      - ./data/dev-db:/var/lib/postgresql/data
    restart: always